### ISSUE TITLE
Can't find chroot #2

### ISSUE THREAD

**Issue by nicking989** [binkybear/AnyKernel2#2]
Hey, I decided to upgrade from the original nethunter on my Nexus 4 which was working perfectly (thanks heaps btw).
My issue is that the nethunter app downloads the chroot and then says "something went wrong verifying the downloaded file. Whoops. Try again."

I also noticed that I had to add:
firmware_list = []
initd_list = []

to the start of the main()  function in build.py else it threw an error partway through building the installer.

Cheers

**Comment by nicking989** [comment]
I got it working by using busybox to manually extract the downloaded tarball to the chroot directory.

**Comment by binkybear** [comment]
Hi @nicking989,

I have moved the installer method to: https://github.com/offensive-security/kali-nethunter
It is under the newinstaller-fj branch, not sure if you used that one or this one.  I highly suggest using that if you used this one.  

Although, the missing list variable issues stays the same on both branches.  I haven't run into any problems with that issue but your fix makes sense so I will go with that.

**Comment by nicking989** [comment]
Thanks, you are right, the new installer works a lot better. I like the snazzy new boot screen However it didn't install the custom kernel. I tried to flash the zImage in the 'lollipop/mako/' directory using "fastboot flash zimage zImage". However it says that the remote partition table doesn't exist. Are there any new kernels that will work with kali and are installable via twrp? or anything I can try?
